language: python
sudo: false

python:
  #- pypy
  - pypy3
  #- "2.7"
  #- "3.2"
  #- "3.3"
  - "3.4"
  #- "3.5"


branches:
  only:
    - upgrade-mongo
    
install: travis_retry .travis/install.sh

script: .travis/run.sh

notifications:
  irc:
    channels:
      - 'irc.freenode.org#webcore'
    use_notice: true
    skip_join: true

after_success:
  - coveralls

services:
  - mongodb
